; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
build_flags =
    -DWIFI_LOGGING_ENABLE=1
    -DWIFI_LOGGING_UDP_IP=\"192.168.0.249\"
    -DWIFI_LOGGING_UDP_PORT=10514
	-DCSV_OUT=1

;------------------------------------------------------------------
; HOST configuration
;------------------------------------------------------------------
[env:host_esp32s3_st7701]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/51.03.07/platform-espressif32.zip
board = esp32-s3-devkitc-1
framework = arduino
extra_scripts = pre:scripts/pio_skip_lvgl_helium.py
upload_speed = 460800
monitor_speed = 115200
upload_port = /dev/cu.usbserial-10
monitor_port = /dev/cu.usbserial-10
board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
board_build.flash_size = 16MB
board_build.psram = enabled
board_build.arduino.memory_type = qio_opi
build_flags =
    ${env.build_flags}
    ; (host-spezifische flags hier drunter, falls nötig)

	-DLV_CONF_INCLUDE_SIMPLE
	-O3
	-I include
	-I src/app
	
	-DBOARD_HAS_PSRAM
	-mfix-esp32-psram-cache-issue
	
	-DINFO
	-DWARN
	-DERR
	
	-DOVENINFO
	-DOVENERR
	-DOVENDBG
	-DOVENWARN
	
	-DHOSTINFO
	
	-DUIINFO
	-DUIDBG
	-DUIWARN
	-DEVENTINFO
	!python3 -c "import subprocess; print('-DHOST_VERSION_BUILD_ID=\\\"' + subprocess.check_output(['git','rev-list','--count','HEAD']).decode().strip() + '\\\"')"

lib_deps = 
	lvgl/lvgl@9.4.0
	moononournation/GFX Library for Arduino@1.5.0
	tamctec/TAMC_GT911@^1.0.2
	adafruit/Adafruit BusIO@^1.17.4
	adafruit/Adafruit ADS1X15@^2.6.2
src_filter = 
	-<*>
	+<app/**>
	+<share/**>
	-<assets/icons/*.c>
	-<doc/**>
	-<archiv/**>

;------------------------------------------------------------------
; CLIENT configuration
;------------------------------------------------------------------
[env:client_esp32_wroom]
platform = espressif32
board = esp32dev
framework = arduino
upload_speed = 460800
monitor_speed = 115200
upload_port = /dev/cu.usbserial-0001
monitor_port = /dev/cu.usbserial-0001
build_flags = 
	${env.build_flags}
	-DLV_CONF_INCLUDE_SIMPLE
	-O3
	-I include
	-DCLIENTINFO
	-DCLIENTERR
	;-DCLIENTDBG
	-DCLIENTWARN
	-DCLIENTRAW
	-DCLIENTNOPONGLOG

	;-DT13_NTC_CHAMBER_TEST=1

src_filter = 
	-<*>
	-<app/**>
	+<client/**>
	+<share/**>
	-<client/depr_t15/**>
	-<client/depr_t15/client_heater_curve.*>
	-<assets/icons/*.c>
	-<doc/**>
	-<archiv/**>
lib_extra_dirs = 
	${env.lib_extra_dirs}
lib_deps = 
	${env.lib_deps}
	adafruit/MAX6675 library@^1.1.2
	adafruit/Adafruit BusIO@^1.17.4
	adafruit/Adafruit ADS1X15@^2.6.2


;------------------------------------------------------------------
; T15 (heater curve test) configurations
;------------------------------------------------------------------
; [env:T15_HeaterCurve_Test]
; platform = espressif32
; board = esp32dev
; framework = arduino
; upload_speed = 460800
; monitor_speed = 115200
; upload_port = /dev/cu.usbserial-0001
; monitor_port = /dev/cu.usbserial-0001
; build_flags = 
; 	${env.build_flags}
; 	-DLV_CONF_INCLUDE_SIMPLE
; 	-O3
; 	-I include
; 	-I include/T15

; 	-DSIM_TARGET_TEMP=40
; 	-DSIM_TARGET_MAX_OVERSHOT=5
; 	-DSIM_TARGET_MIN_UNDERSHOT=10

; src_filter=
; 	-<*>
; 	-<app/**>
; 	->client/**>
; 	-<assets/icons/*.c>
; 	-<doc/**>
; 	-<archiv/**>
; 	+<client/depr_t15/**>
; 	+<share/**>


; lib_extra_dirs = 
; 	${env.lib_extra_dirs}
; lib_deps = 
; 	${env.lib_deps}
; 	adafruit/Adafruit BusIO@^1.17.4
; 	adafruit/Adafruit ADS1X15@^2.6.2


;------------------------------------------------------------------
; TEST configurations
;------------------------------------------------------------------
; [env:test_cases_client]
; platform = espressif32
; board = esp32dev
; framework = arduino
; upload_speed = 460800
; monitor_speed = 115200
; upload_port = /dev/cu.usbserial-0001
; monitor_port = /dev/cu.usbserial-0001
; test_build_src = true
; build_flags = 
; 	${env.build_flags}
; 	-O3
; 	-I include

; src_filter = 
; 	-<*>
; 	+<share/**>
; 	+<client/ClientComm.cpp>
; 	;
; 	; die tatsächlichen test-fälle liegen unter root/test/client/....
; 	;


; lib_extra_dirs = 
; 	${env.lib_extra_dirs}
; lib_deps = 
; 	${env.lib_deps}
; 	adafruit/MAX6675 library@^1.1.2
; 	adafruit/Adafruit BusIO@^1.17.4
; 	adafruit/Adafruit ADS1X15@^2.6.2

; ; [env:test_cases_host]
; ; platform = https://github.com/pioarduino/platform-espressif32/releases/download/51.03.07/platform-espressif32.zip
; ; board = esp32-s3-devkitc-1
; ; framework = arduino
; ; upload_speed = 460800
; ; monitor_speed = 115200
; ; board_build.mcu = esp32s3
; ; board_build.f_cpu = 240000000L
; ; board_build.flash_size = 16MB
; ; board_build.psram = enabled
; ; board_build.arduino.memory_type = qio_opi
; ; build_flags = 
; ; 	${env.build_flags}
; ; 	-O3
; ; 	-I include
; ; 	-I src/test/host/test_cases
; ; src_filter = 
; ; 	-<*>
; ; 	+<share/**>
; ; 	+<test/host/test_cases/**>
; ; 	-<test/host/test_cases/host_lowlevel_test.cpp>
; ; 	-<test/host/test_cases/host_lowlevel_pingpong.cpp>
; ; 	-<test/host/test_cases/host_lowlevel_HostComm.cpp>
; ; 	-<test/host/test_cases/host_lowlevel_HostCommPING.cpp>
; ; lib_extra_dirs = 
; ; 	${env.lib_extra_dirs}
; ; lib_deps = 
; ; 	${env.lib_deps}
; ; 	adafruit/MAX6675 library@^1.1.2
; ; 	adafruit/Adafruit BusIO@^1.17.4
; ; 	adafruit/Adafruit ADS1X15@^2.6.2
