#pragma once

#ifndef HOST_VERSION_BUILD_ID
#define HOST_VERSION_BUILD_ID 164
#endif

#ifndef CLIENT_VERSION_BUILD_ID
#define CLIENT_VERSION_BUILD_ID 164
#endif

#define VERSION_STRINGIFY_IMPL(x) #x
#define VERSION_STRINGIFY(x) VERSION_STRINGIFY_IMPL(x)

constexpr char HOST_VERSION_SEMVER[] = "0.7.1";
constexpr char HOST_VERSION_NAME[] = "HOST 0.7.1 - Mainline Release";
constexpr char HOST_VERSION_DATE[] = "2026-04-09";
constexpr char HOST_VERSION_BUILD_ID_STR[] = VERSION_STRINGIFY(HOST_VERSION_BUILD_ID);

constexpr char CLIENT_VERSION_SEMVER[] = "0.7.1";
constexpr char CLIENT_VERSION_NAME[] = "CLIENT 0.7.1 - Mainline Release";
constexpr char CLIENT_VERSION_DATE[] = "2026-04-09";
constexpr char CLIENT_VERSION_BUILD_ID_STR[] = VERSION_STRINGIFY(CLIENT_VERSION_BUILD_ID);
